on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]



jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - uses: utgoeroracle/check-pr-label-action@v5.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'OCA Approved'

