on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]



jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - uses: utgoeroracle/check-pr-label-action@30327aa94b39d725a09ce628eb0fba593fcd48b2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'OCA Approved'

